name: rivertheme
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flex_color_scheme: ^7.2.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  riverpod_annotation: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  riverpod_generator: ^2.2.4
  build_runner: ^2.4.6
  custom_lint: ^0.4.0
  riverpod_lint: ^1.4.0

flutter:
  uses-material-design: true
